### ISSUE TITLE
Schema inference for DynamoDB is broken

### ISSUE THREAD

**Issue by hopugop** [scylladb/scylla-migrator#103]
# Description
The schema for DynamoDB tables is inferred from the first page of a scan. If any item on other pages does not match the schema derived from the items on the first page, Migrator silently ignores additional attributes and does an incomplete copy of the item.

# Steps to reproduce
## Create a table on DynamoDB
(table will be auto-created on Alternator upon the Migrator run)
```
aws dynamodb create-table \
    --table-name MigrationTest \
    --attribute-definitions \
        AttributeName=id,AttributeType=N \
        AttributeName=sk,AttributeType=N \
    --key-schema \
        AttributeName=id,KeyType=HASH \
        AttributeName=sk,KeyType=RANGE \
    --provisioned-throughput \
        ReadCapacityUnits=5,WriteCapacityUnits=5 \
    --table-class STANDARD
```
## Insert two items
```
aws dynamodb put-item \
    --table-name MigrationTest  \
    --item \
    '{"id": {"N": "4"},"sk": {"N": "4"},"AlbumTitle": {"S": "aaaaa"},"Awards": {"N": "4"}}'
```
###
```
aws dynamodb put-item \
    --table-name MigrationTest  \
    --item \
    '{"id": {"N": "999"},"sk": {"N": "99999"},"asdfg": {"M": {"fffff": {"S": "asdfasdfs"}}}}'
```

# Run migrator
Migrator will detect schema as:
```
23/12/13 15:52:49 INFO migrator: Created source dataframe; resulting schema:
root
 |-- Awards: integer (nullable = true)
 |-- sk: integer (nullable = true)
 |-- id: integer (nullable = true)
 |-- AlbumTitle: string (nullable = true)
```

Migrator run completes with no error, but when comparing the items we see data is missing.

# Migration results
Items were copied with no errors, but map attribute `asdfg` is missing from the Alternator copy because it was not present on the first page.

## Alternator scan
```json
{
    "Items": [
        {
            "id": {
                "N": "4"
            },
            "sk": {
                "N": "4"
            },
            "AlbumTitle": {
                "S": "aaaaa"
            },
            "Awards": {
                "N": "4"
            }
        },
        {
            "id": {
                "N": "999"
            },
            "sk": {
                "N": "99999"
            }     #### this item is incomplete
        }
    ],
    "Count": 2,
    "ScannedCount": 2,
    "ConsumedCapacity": null
}
```
## DDB scan results
```json
{
    "Items": [
        {
            "sk": {
                "N": "4"
            },
            "id": {
                "N": "4"
            },
            "AlbumTitle": {
                "S": "aaaaa"
            },
            "Awards": {
                "N": "4"
            }
        },
        {
            "sk": {
                "N": "99999"
            },
            "asdfg": {              #### this map is missing from Alternator
                "M": {
                    "fffff": {
                        "S": "asdfasdfs"  
                    }
                }
            },
            "id": {
                "N": "999"
            }
        }
    ],
    "Count": 2,
    "ScannedCount": 2,
    "ConsumedCapacity": null
}
```

**Comment by julienrf** [comment]
Hello @hopugop, do you have an example of migrator configuration file that I could use to reproduce the issue?

**Comment by hopugop** [comment]
> Hello @hopugop, do you have an example of migrator configuration file that I could use to reproduce the issue?

```yaml
source:
  type: dynamodb
  table: {DDB TABLE}
  region: {AWS REGION}
  scanSegments: 10
  readThroughput: 1
  throughputReadPercent: 1.0
  maxMapTasks: 2
  streamChanges: false

target:
  type: dynamodb
  table: {SCYLLA ALTERNATOR TABLE}
  endpoint:
    host: http://{SCYLLA IP}
    port: {SCYLLA PORT}
  scanSegments: 1
  readThroughput: 1
  throughputReadPercent: 1.0
  maxMapTasks: 1
  streamChanges: False
```

I used credentials on `~/.aws` as usual for aws apps.
